config/routes.rb
Rails.application.routes.draw do

  
  
  
  resources :users do
    resources :tasks
  end
  
  get "/" => 'users#login', as: :home
  get "/login" => 'users#login', as: :login
  post "/login" => 'users#login_check'
  get "/profile/edit" => 'users#edit', as: :edit_profile
  put "/profile" => 'users#update', as: :profile
  delete "/profile" => 'users#destroy'
  get "/profile" => 'users#show'
  
  get "/tasks" => 'tasks#index', as: :my_tasks  #identical to users_tasks except you're logged in
  get "/tasks/new" => 'tasks#new', as: :new_my_task
  post "/tasks/new" => 'tasks#create'
  get "/tasks/:id/edit" => 'tasks#edit', as: :edit_my_task
  put "/tasks/:id/edit" => 'tasks#update'
  patch "/tasks/:id/edit" => 'tasks#update'
  delete "/tasks/:id" => 'tasks#destroy'
  get "/tasks/:id" => 'tasks#show', as: :my_task
    
  put "/tasks/:id/done" => 'tasks#done', as: :mark_done
  put "/tasks/:id/undone" => 'tasks#undone', as: :mark_undone
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id        :integer          not null, primary key
#  name      :string
#  completed :boolean          default(FALSE)
#  user_id   :integer
#

class Task < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  
  # updates to complete if not completed
  #
  # returns a Boolean if able to update
  def mark_done
    if !self.completed
      self.update(completed: true)
    else
      false
    end
  end
  
  # updates to not complete if already completed
  #
  # returns a Boolean if able to update
  def mark_undone
    if self.completed
      self.update(completed: false)
    else
      false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  helper TasksHelper
  # show all records
  def index
    if params["user_id"].blank?
      set_user_if_available
    else
      @user = User.find(params["user_id"])
    end
    @tasks = @user.tasks
  end
  
  # receive form to create a new record
  def create
    current_user
    @task = Task.new(params_permitted)
    if @task.save
      redirect_to my_tasks_path, :notice => "Successfully added."
    else
      @path = new_my_task_path
      render "new"
    end
  end
  
  # look at form to create a new record
  def new
    current_user
    @task = @user.tasks.new()
    @path = new_my_task_path
  end
  
  # show a single record
  def show
    current_user
    set_task
  end
  
  # see a form to update a single record
  def edit
    current_user
    set_task
    @path = edit_my_task_path
  end
  
  # update a single record from form
  def update
    current_user
    @task = Task.find(params["id"])
    if @task.user_id != @user.id
      redirect_to profile_path
    else 
      if @task.update(params_permitted)
        redirect_to my_tasks_path, :notice => "Successfully updated!"
      else
        @path = edit_my_task_path
        render "edit"
      end
    end
  end
  
  # delete this record and all its associations
  def destroy
    current_user
    set_task
    if @task.destroy
      redirect_to my_tasks_path, :notice => "Successfully deleted."
    else
      redirect_to my_tasks_path, :notice => "Not able to delete."
    end
  end
  
  def done
    current_user
    set_task
    @task.mark_done
    render json: @task
  end
  
  def undone
    current_user
    set_task
    @task.mark_undone
    render json: @task
  end
  
  private
  def set_task
    if params[:id].blank?
      @task = Task.new(user_id: @user.id)
    else
      @task = Task.find(params[:id])
    end
  end
  
  def params_permitted
    params["task"].permit(:name, :completed, :user_id)
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
  def this_users_task?
    @user.id == @task.user_id
  end
end

app/views/tasks/_form.html.erb
<%= @task.inspect %>

<%= form_for @task, url: @path do |f| %>
  <%= f.text_field("name", placeholder: "Type in the task.") %>
  <%= f.hidden_field("user_id") %>
  <%= f.label("completed") %>
  <%= f.check_box("completed") %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<ul>
  <% @task.errors.messages.each do |error| %>
    <li><%= error[1] %></li>
  <% end %>
</ul>


<%= render "form" %>

app/views/tasks/index.html.erb
<% if this_user? %>
  <h3>My Tasks</h3>
<% else %>
  <h3><%= @user.name %>'s Tasks</h3>
<% end %>

<ul>
  <% @tasks.each do |task| %>
    <% if this_user? %>
      <li class="<%= "done" if task.completed %>"><%= link_to task.name, my_task_path(task.id) %> 
        <%= link_to_if(task.completed, "Mark Undone", mark_undone_path(task.id), {class: "done mark--undone", "data-id": "#{task.id}", method: :put}) do
        link_to "Mark Done", mark_done_path(task.id), {class: "mark--done", "data-id": "#{task.id}", method: :put}
        end%>
      </li>
    <% else %>
      <li><%= link_to task.name, user_task_path(task.user_id, task.id) %></li>
    <% end %>
  <% end %>
</ul>

<% if this_user? %>
  <%= link_to "Add A Task", new_my_task_path %>
  <%= link_to "My Profile", profile_path %>
<% else %>
  <%= link_to "#{@user.name}'s Profile", @user %>
<% end %>

app/views/tasks/new.html.erb
<ul>
  <% @task.errors.messages.each do |error| %>
    <li><%= error[1] %></li>
  <% end %>
</ul>


<%= render "form" %>

app/views/tasks/show.html.erb
<% if this_users_task? %>
  <h3>My Task</h3>
  <ul class="mark">
   <li><%= link_to_if(@task.completed, "Mark Undone", mark_undone_path(@task.id), {class: "mark--undone, done", "data-id": "#{@task.id}", method: :put}) do
  link_to "Mark Done", mark_done_path(@task.id), {class: "mark--done", "data-id": "#{@task.id}", method: :put}
  end%></li>
   <li><%= link_to "Edit Task", edit_my_task_path %></li>
   <li><%= link_to "Delete Task", my_task_path, data: {method: :delete, confirm: "Are you sure?"} %></li> 
  </ul>
  
<% end %>
<ul>  
  <% @task.attributes.each do |attribute| %>
    <li><%= "#{attribute[0]}: #{attribute[1]}" %></li>
  <% end %>
</ul>

<p>Associations:</p>
<ul>
  <% Task.reflections.keys.each do |key| %>
      <% @association = @task.method(key).call %>
      <% if @association.respond_to? :each %>
          <li><%= @association.name %></li>
          <ul>
          <% if @association.length == 0 %>
            <li>None</li>
          <% end %>
          <% @association.each do |p| %>
              <li> p.name </li>
          <% end %>
          </ul>
      <% else %>
        <li><%= "#{@association.class}: #{@association.name}"  %></li>
      <% end %>
  <% end %>        
</ul>

<% if this_users_task? %>
  <%= link_to "Add A Task", new_my_task_path %>
  <%= link_to "Return To All Tasks", my_tasks_path %>
  <%= link_to "My Profile", profile_path %>
<% else %>
  <%= link_to "#{@task.user.name}'s Profile", @task.user %>
<% end %>