config/routes.rb
Rails.application.routes.draw do

  
  
  
  resources :users do
    resources :tasks
  end
  
  get "/" => 'users#login', as: :home
  get "/login" => 'users#login', as: :login
  post "/login" => 'users#login_check'
  get "/profile/edit" => 'users#edit', as: :edit_profile
  put "/profile" => 'users#update', as: :profile
  delete "/profile" => 'users#destroy'
  get "/profile" => 'users#show'
  
  get "/tasks" => 'tasks#index', as: :my_tasks  #identical to users_tasks except you're logged in
  get "/tasks/new" => 'tasks#new', as: :new_my_task
  post "/tasks/new" => 'tasks#create'
  get "/tasks/:id/edit" => 'tasks#edit', as: :edit_my_task
  put "/tasks/:id/edit" => 'tasks#update'
  patch "/tasks/:id/edit" => 'tasks#update'
  delete "/tasks/:id" => 'tasks#destroy'
  get "/tasks/:id" => 'tasks#show', as: :my_task
    
  put "/tasks/:id/done" => 'tasks#done', as: :mark_done
  put "/tasks/:id/undone" => 'tasks#undone', as: :mark_undone
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string
#  email              :string
#  password_encrypted :string
#

class User < ActiveRecord::Base
  include Login
  
  has_many :tasks
  
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password_encrypted, presence: true
  
  # returns an Array of Task objects that are incomplete
  #
  # returns an Array of Tasks
  def incomplete_tasks
   self.tasks.select{|task| !task.completed} 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # get "/login" => 'users#login', as: :login
  # get "/users" => 'users#index', as: :users
  # get "/users/new" => 'users#new', as: :new_user
  # post "/users/new" => 'users#create'
  # get "profile/edit" => 'users#edit', as: :edit_profile
  # put "profile/edit" => 'users#update'
  # delete "profile" => 'users#delete'
  # get "/profile" => 'users#profile', as: :profile
  # get "/users/:id" => 'users#show', as: :user     #identical to profile, except you're not logged in
  
  
  def login
    clear_session
    @user = User.new
  end
  
  def login_check
    find_user_by_email
    if @user.valid_password?(params["users"]["password"])
      set_session
      redirect_to profile_path
    else
      render "login"
    end
  end
  
  # show all records
  def index
    set_user_if_available
    @users = User.all
  end
  
  # look at form to create a new record
  def new
    @user = User.new
  end
  
  # receive form to create a new record
  def create
    @user = User.new(params_permitted)
    if @user.save
      set_session
      redirect_to profile_path
    else
      render "new"
    end
  end
  
  # see a form to update a single record
  def edit
    current_user
  end
  
  # update a single record from form
  def update
    current_user
    if @user.update(params_permitted)
      redirect_to profile_path
    else
      render "edit"
    end
  end
  
  # delete this record and all its associations
  def destroy
    current_user
    if @user.delete
      clear_session
      redirect_to users_path
    else
      redirect_to profile_path
    end
  end
  
  # show a single record
  def show
    set_user_if_available
    set_this_user
  end
  
  private
  def params_permitted
    params["user"].permit(:email, :name, :password)
  end
  
  def set_this_user
    if params[:id].blank?
      @this_user = @user
    else
      @this_user = User.find(params[:id])
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper

  # cache = ActiveSupport::Cache::MemoryStore.new
  #
  # cache.read('city')   # => nil
  # cache.write('city', "Duckburgh")
  # cache.read('city')   # => "Duckburgh"


  # checks the sesion id and gets the current user
  # or redirects to the home_path
  #
  # returns @user or redirects
  def current_user
    if session_id
      @user = User.find(session_id)
    else
      clear_session
      redirect_to home_path
    end 
  end 
  
  # set user if available
  #
  # returns a user
  def set_user_if_available    
    if session_id
      @user = User.find(session_id)
    else
      @user = User.new
    end
  end
  
  # checks if this user matches the session's user
  #
  # returns a Boolean
  def this_user?
    @user.id == session_id
  end
  
  # returns the sesion id
  #
  # returns an Integer or nil
  def session_id
    session[:id]
  end

  # clears the session
  #
  # returns nils
  def clear_session
    session.clear
  end
  
  # sets the session
  #
  # returns the session
  def set_session
    session[:id] = @user.id
  end
  
  # saves the user and sets the session to this user
  #
  # returns the sesion
  def save_user_and_set_session
    @user.save
    set_session
  end
  
  # finds this email address and returns a User object
  #
  # returns a user object
  def find_user_by_email
    @user = User.where("email" => params["users"]["email"]).first
    if @user == nil
      @user = User.new
    end
  end

end

app/views/users/show.erb
<% if @this_user == @user %>
  <h3>My Profile</h3>
  <%= link_to "Edit Profile", edit_profile_path %>
  <%= link_to "Delete Profile", profile_path, data: {method: :delete, confirm: "Are you sure?"} %>
<% end %>
<ul>
  <% @this_user.attributes.each do |attribute| %>
    <li><%= "#{attribute[0]}: #{attribute[1]}" %></li>
  <% end %>
</ul>

<p>Associations:</p>
<ul>
  <% User.reflections.keys.each do |key| %>
      <% @association = @this_user.method(key).call %>
      <% if @association.respond_to? :each %>
          <li><%= @association.name %></li>
          <ul>
          <% if @association.length == 0 %>
            <li>None</li>
          <% end %>
          <% @association.each do |p| %>
          <% if @this_user == @user %>
              <li> <%= link_to p.name, my_task_path(p.id) %></li>
          <% else  %>
              <li> <%= link_to p.name, p %></li>
          <% end %>
          

          <% end %>
          </ul>
      <% else %>
        <li><%= "#{@association.class}: #{@association.name}"  %></li>
      <% end %>
  <% end %>        
</ul>

<% if @this_user == @user %>
  <%= link_to "Add A Task", my_new_task_path %>
<% end %>

app/views/users/show.html.erb
<% if @this_user == @user %>
  <h3>My Profile</h3>
  <%= link_to "Edit Profile", edit_profile_path %>
  <%= link_to "Delete Profile", profile_path, data: {method: :delete, confirm: "Are you sure?"} %>
<% end %>
<ul>
  <% @this_user.attributes.each do |attribute| %>
    <li><%= "#{attribute[0]}: #{attribute[1]}" %></li>
  <% end %>
</ul>

<p>Associations:</p>
<ul>
  <% User.reflections.keys.each do |key| %>
      <% @association = @this_user.method(key).call %>
      <% if @association.respond_to? :each %>
          <li><%= @association.name %></li>
          <ul>
          <% if @association.length == 0 %>
            <li>None</li>
          <% end %>
          <% @association.each do |p| %>
          <% if @this_user == @user %>
              <li> <%= link_to p.name, my_task_path(p.id) %></li>
          <% else  %>
              <li> <%= link_to p.name, user_task_path(p.user_id, p.id) %></li>
          <% end %>
          

          <% end %>
          </ul>
      <% else %>
        <li><%= "#{@association.class}: #{@association.name}"  %></li>
      <% end %>
  <% end %>        
</ul>

<% if @this_user == @user %>
  <%= link_to "All My Tasks", my_tasks_path %>
  <%= link_to "Add A Task", new_my_task_path %>
<% end %>